export const PROJECT_NAME_MAX_LENGTH = 50;
export const SNIPPET_TITLE_MAX_LENGTH = 100;
export const FIELD_LABEL_MAX_LENGTH = 50;
export const FIELD_VALUE_MAX_LENGTH = 10000;
export const MASTER_PASSWORD_MAX_LENGTH = 128;

export const LIMITS = {
  PROJECT_NAME: 50,
  SNIPPET_TITLE: 100,
  FIELD_LABEL: 50,
  FIELD_VALUE: 10000,
  MASTER_PASSWORD: 128,
  MASTER_PASSWORD_MIN: 12,
  MASTER_PASSWORD_LEGACY_MIN: 8,
  MASTER_PASSWORD_MIN_UNIQUE: 4,
  MAX_PROJECTS: 50,
  MAX_SNIPPETS_PER_PROJECT: 200,
  MAX_FIELDS_PER_SNIPPET: 20,
  MAX_IMPORT_FILE_SIZE: 2 * 1024 * 1024, // 2MB
};

export const SECURITY = {
  PBKDF2_ITERATIONS: 600000,
  LEGACY_PBKDF2_ITERATIONS: 100000,
};
