export const PROJECT_NAME_MAX_LENGTH = 50;
export const SNIPPET_TITLE_MAX_LENGTH = 100;
export const FIELD_LABEL_MAX_LENGTH = 50;
export const FIELD_VALUE_MAX_LENGTH = 10000;
export const MASTER_PASSWORD_MAX_LENGTH = 128;
